### ISSUE TITLE
Add copyright notice

### ISSUE THREAD

**Issue by JonBunator** [remondevries/tokyonight-gitkraken-theme#1]
You copied parts of the *.readme from my repository: https://github.com/JonBunator/gitkraken-custom-themes
Especially the logo.
Please add my copyright notice or remove the readme/logo. Thanks!

**Comment by remondevries** [comment]
Sorry about that, I was not aware you create that logo I thought this was from GitKraken itself. I would like to add a special note to the bottom of the readme thanking you, what would you like that to be? I was thinking:

--

# Thanks to..

@JonBunator creator of [Collection of custom themes for GitKraken](https://github.com/JonBunator/gitkraken-custom-themes)

**Comment by JonBunator** [comment]
That would be great. Thank you :)

**Comment by remondevries** [comment]
Just finished doing that, I did adjust the logo because this is not a collection of themes just one theme. Would you be interested in me adding this theme to your theme collection?

**Comment by JonBunator** [comment]
> Just finished doing that, I did adjust the logo because this is not a collection of themes just one theme. Would you be interested in me adding this theme to your theme collection?

Your theme looks great. Good job :)
You can create a PR if you want to add it. But I might change some small things later on if you're okay with this

**Comment by remondevries** [comment]
Thats fine, feel free to do so. let me plan this in. 😄
